### ISSUE TITLE
Error with 'hotfix review' command

### ISSUE THREAD

**Issue by sgringwe** [zencoder/zenflow#39]
I am receiving this error when I try to open a PR for my hotfix:
```: bundle exec zenflow hotfix review
-----> Looking up pull request for hotfix/copy-expiration-date
/Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/lib/zenflow/helpers/pull_request.rb:64:in `[]': no implicit conversion of String into Integer (TypeError)
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/lib/zenflow/helpers/pull_request.rb:64:in `[]'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/lib/zenflow/helpers/pull_request.rb:18:in `block in find_by_ref'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/lib/zenflow/helpers/pull_request.rb:17:in `each'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/lib/zenflow/helpers/pull_request.rb:17:in `detect'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/lib/zenflow/helpers/pull_request.rb:17:in `find_by_ref'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/lib/zenflow/helpers/branch_commands/review.rb:16:in `create_pull_request'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/lib/zenflow/helpers/branch_commands/review.rb:11:in `review'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/zenflow-c8317152aba4/bin/zenflow:16:in `<top (required)>'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/zenflow:23:in `load'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/zenflow:23:in `<main>'```

**Comment by jondkinney** [comment]
IIRC this is due to a missing zenflow token in `.git/config` or `~/.gitconfig`. Were you able to get past this after manually adding a token @sgringwe?

There is some facility to add that token automatically, but it only happens once, and if you miss it then it's a bit of a pain to have to put in manually. Definitely some room for improvement there.

**Comment by sgringwe** [comment]
@jondkinney oh hey. this was indeed fixed but i'm not sure how or why. i think that your guess is correct though.
